/******************************************************************/
/* CGI Wrapper Program to allow access to scripts on HTTPD server */
/* Written by:  Nathan Neulinger  <nneul@umr.edu>                 */
/* Includes many fixes and improvements as suggested by users     */
/******************************************************************/

#include "config.h"		/* Generated by Configure */
#include "cgiwrap.h"    /* Header File Includes */
#include "util.h"	/* Misc. Utility Routines and Defines */
#include "debug.h"	/* Prototypes for debuygging routines */

/* Debugging Trigger */
extern int CONF_DEBUG;


/***/
/**  Check If User Listed In File
/***/
int UserInFile(char *filename, char *user)
{
	FILE *file;
	int result = 0;
	char temp[200];

	if ( (file=fopen(filename,"r")) == NULL )
	{
		DoPError("Couldn't Open User List File");
	}
	
	while ( !feof(file) )
	{
		fscanf(file,"%s",temp);
		if ( !strcmp(temp,user) )
		{
			fclose(file);
			return 1;
		}
	}
	fclose(file);

	return 0;
}

/***/
/**  Check if should allow user
/***/
int CheckAllowUser(char *user)
{

#if defined(CONF_ALLOWFILE)
	return UserInFile(CONF_ALLOWFILE,user);
#elif defined(CONF_ALLOW_NISGROUP)
	return CheckAllowNISGroup(user);
#endif

	return 1;
}


/***/
/**  Check if should deny user
/***/
int CheckDenyUser(char *user)
{
#if defined(CONF_DENYFILE)
	return UserInFile(CONF_DENYFILE,user);
#elif defined(CONF_DENY_NISGROUP)
	return CheckDenyNISGroup(user);
#endif

	return 0;
}

