/******************************************************************/
/* CGI Wrapper Program to allow access to scripts on HTTPD server */
/* Written by:  Nathan Neulinger  <nneul@umr.edu>                 */
/* Includes many fixes and improvements as suggested by users     */
/*----------------------------------------------------------------*/
/* Provides various levels of security depending on which options */
/* are chosen in config.h                                         */
/******************************************************************/

#include "config.h"		/* Generated by Configure */

#include <stdio.h>		/* For passing data into called script */
#include <ctype.h> 

#if defined(I_STRING)		/* string routines */
#include <string.h>
#else
#include <strings.h>
#endif



void DEBUG_Msg (char *msg);
void DEBUG_Str (char *msg, char *var);
void DEBUG_StrStr (char *msg, char *var, char *var2);
void DEBUG_Int (char *msg, int var);
