#include "config.h"		/* Generated by Configure */
/***/
/**   Display an error message and exit the program */
/***/
void MyPError (void)
{
	extern int errno;

#if defined(HAS_SYS_ERRLIST)
	extern char *sys_errlist[];
#endif

#if defined(HAS_SYS_ERRLIST)
	printf("%s", sys_errlist[errno]);
#elif defined(HAS_STRERROR)
	printf("%s", strerror(errno));
#endif

	printf(" (%d)", errno);
}
